export enum FieldType {
    textbox = 'textbox',
    textarea = 'textarea',
    numberbox = 'numberbox',
    dropdown = 'dropdown',
    radiobuttons = 'radiobuttons',
    checkbox = 'checkbox',
    datepicker = 'datepicker',
    daterangepicker = 'daterangepicker',
    chips = 'chips',
    multiselection = 'multiselection',
    iconpicker = 'iconpicker',
    file = 'file',
    custom = 'custom',
    listinputs = 'listinputs',
}